### ISSUE TITLE
Add Documentation for Getting Started using DHP

### ISSUE THREAD

**Issue by AnirudhTiwari** [beckn/DHP-Specs#76]

**Comment by ravi-prakash-v** [comment]
This is done in wiki. We have

[Getting Started: Enabling Ambulance Booking using DHP](https://github.com/dhp-project/DHP-Specs/wiki/Getting-Started:-Enabling-Ambulance-Booking-using-DHP)
[Getting Started: Enabling Digital Consultation using DHP](https://github.com/dhp-project/DHP-Specs/wiki/Getting-Started:-Enabling-Digital-Consultation-using-DHP)
[Getting Started: Enabling Physical Consult using DHP](https://github.com/dhp-project/DHP-Specs/wiki/Getting-Started:-Enabling-Physical-Consult-using-DHP)
