### ISSUE TITLE
Add Gateway setup documentation in Getting Started wiki

### ISSUE THREAD

**Issue by anirudhTiwari20** [beckn/DHP-Specs#79]

**Comment by ravi-prakash-v** [comment]
@anirudhTiwari20 Gateway is independent of use case.

**Comment by ravi-prakash-v** [comment]
Editing the title from `Add Gateway setup documentation in Getting Started wiki for Ambulance Booking` to `Add Gateway setup documentation in Getting Started wiki`

**Comment by ravi-prakash-v** [comment]
Gateway setup is any ways generic and does not need a separate documentation. So closing this.
